#include "exception.h"
#include "printf.h"
#include "list.h"
#include "util.h"
#include "peripheral.h"
#include "mini_uart.h"
#include "memory.h"
#include "string.h"
#include "timer.h"

enum task_status{
    BLANK,
    WAITING,
    EXECUTING,
};

typedef struct task{
    list_head_t         anchor;
    enum task_status    status;
    uint8_t             priority;   // smaller number is more preemptive
    task_handler_t      handler;
} task_t;

static LIST_HEAD(blank_tasks_q);
static LIST_HEAD(waiting_tasks_q);

task_t* get_blank_task(void);
void add_waiting_task(task_t *task);
void waiting_task_exec(void);

void get_esr_fields(uint32_t OUT *ec_ref, uint32_t OUT *il_ref, uint32_t OUT *iss_ref, uint8_t el);

void handler_el1_0(void){
    uart_poll_putln("synchronous exception from current EL, using SP_EL0\n");
}

void handler_el1_1(void){
    printf("IRQ exception from current EL, using SP_EL0\n");
}

void handler_el1_2(void){
    printf("FIQ exception from current EL, using SP_EL0\n");
}

void handler_el1_3(void){
    printf("SError exception from current EL, using SP_EL0\n");
}

// synchronous exception from current EL, using SP_ELx
void handler_el1_4(void){
    uint32_t ec, il, iss;
    get_esr_fields(&ec, &il, &iss, 1);
    uart_poll_puts("handler_el1_8: ec = 0x");
    uart_poll_puts(uint_to_hex_str(ec, -1, NULL));
    uart_poll_puts(", il = 0x");
    uart_poll_puts(uint_to_hex_str(il, -1, NULL));
    uart_poll_puts(", iss = 0x");
    uart_poll_putln(uint_to_hex_str(iss, -1, NULL));
}

// IRQ exception from current EL, using SP_ELx
void handler_el1_5(void){
    task_t *task = NULL;
    
    if(get32(IRQ_PENDING_1) & IRQ_AUX_INT){         // UART IRQ
        // because we process asynchronous IO in this block, we can't use any asynchronous IO here.
        if(get32(AUX_MU_IIR) & AUX_IRQ_RX){         // Receiver holds valid byte
            uart_rx_clr();
            task = get_blank_task();
            task->status = WAITING;
            task->priority = 3;
            task->handler = handler_uart_rx;
        }else if(get32(AUX_MU_IIR) & AUX_IRQ_TX){   // Transmit holding register empty
            uart_tx_clr();
            task = get_blank_task();
            task->status = WAITING;
            task->priority = 3;
            task->handler = handler_uart_tx;
        }
    }else if(get32(CORE0_IRQ_SOURCE) & CNTPNSIRQ){  // timer IRQ
        core_timer_disable();
        task = get_blank_task();
        task->status = WAITING;
        task->priority = 1;
        task->handler = handler_el1_5_timer_event;
    }else{
        printf("IRQ exception from current EL, using SP_ELx\n");
    }

    if(task){
        add_waiting_task(task);
        waiting_task_exec();
    }
}

void handler_el1_6(void){
    printf("FIQ exception from current EL, using SP_ELx\n");
}

void handler_el1_7(void){
    printf("SError exception from current EL, using SP_ELx\n");
}

// synchronous exception from lower EL, at least one lower EL is AArch64
void handler_el1_8(void){
    uint32_t ec, il, iss;
    get_esr_fields(&ec, &il, &iss, 1);
    switch(ec){
        case 0x15:  // SVC instruction execution
            uart_poll_putln("User program synchronous exception generated by the SVC instruction.");
            break;
        default:
            uart_poll_puts("handler_el1_8: ec = 0x");
            uart_poll_puts(uint_to_hex_str(ec, -1, NULL));
            uart_poll_puts(", il = 0x");
            uart_poll_puts(uint_to_hex_str(il, -1, NULL));
            uart_poll_puts(", iss = 0x");
            uart_poll_putln(uint_to_hex_str(iss, -1, NULL));
            break;
    }
}

void handler_el1_9(void){
    printf("IRQ exception from lower EL, at least one lower EL is AArch64\n");
}

void handler_el1_10(void){
    printf("FIQ exception from lower EL, at least one lower EL is AArch64\n");
}

void handler_el1_11(void){
    printf("SError exception from lower EL, at least one lower EL is AArch64\n");
}

void handler_el1_12(void){
    uart_poll_putln("synchronous exception from lower EL, all lower ELs are AArch32\n");
}

void handler_el1_13(void){
    printf("IRQ exception from lower EL, all lower ELs are AArch32\n");
}

void handler_el1_14(void){
    printf("FIQ exception from lower EL, all lower ELs are AArch32\n");
}

void handler_el1_15(void){
    printf("SError exception from lower EL, all lower ELs are AArch32\n");
}

void get_esr_fields(uint32_t OUT *ec_ref, uint32_t OUT *il_ref, uint32_t OUT *iss_ref, uint8_t el){
    uint32_t esr = 0, ec = 0, il = 0, iss = 0;
    switch(el){
        case 1:
            asm volatile("mrs %0, esr_el1": "=r"(esr));
            break;
        case 2:
            asm volatile("mrs %0, esr_el2": "=r"(esr));
            break;
        case 3:
            asm volatile("mrs %0, esr_el3": "=r"(esr));
            break;
    }
    ec = esr >> 26;
    il = esr >> 25 & 0x1;
    iss = esr & ((1 << 25) - 1);

    if(ec_ref != NULL)  *ec_ref = ec;
    if(il_ref != NULL)  *il_ref = il;
    if(iss_ref != NULL)  *iss_ref = iss;
}

task_t* get_blank_task(void){
    task_t *task = NULL;
    if(list_is_empty(&blank_tasks_q)){
        task = (task_t*)startup_alloc(sizeof(task_t));
        if(task == NULL)
            task = (task_t*)malloc(sizeof(task_t));
    }else{
        task = container_of(blank_tasks_q.next, task_t, anchor);
        list_remove(&task->anchor);
    }

    if(task != NULL){
        task->anchor.prev = task->anchor.next = &task->anchor;
        task->status = BLANK;
        task->priority = 255;
        task->handler = NULL;
    }
    
    return task;
}

void add_waiting_task(task_t *task){
    if(task){
        list_head_t *prev = &waiting_tasks_q;
        list_head_t *next = prev->next;

        while(!list_is_head_node(next, &waiting_tasks_q) && container_of(next, task_t, anchor)->priority <= task->priority){
            prev = next;
            next = next->next;
        }

        list_add(&task->anchor, prev, next);
    }
}

void waiting_task_exec(void){
    task_t *task = NULL;
    while(!list_is_empty(&waiting_tasks_q)){
        task = container_of(waiting_tasks_q.next, task_t, anchor);
        if(task->status != WAITING) break;
        enable_interrupt_all();
        task->status = EXECUTING;
        task->handler();
        disable_interrupt_all();

        task->status = BLANK;
        list_remove(&task->anchor);
        list_append(&task->anchor, &blank_tasks_q);
    }
}